# fly.toml app configuration file generated for okx-grid-bot on 2026-04-12T21:31:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'okx-grid-bot'
primary_region = 'gru'

[build]

[machines]
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
